### ISSUE TITLE
Would your provide the pretrained model in imagenet?

### ISSUE THREAD

**Issue by KeyKy** [mundher/NSFW#1]
Would your provide the pretrained model in imagenet? tensorflow or caffe will be appreciated.

**Comment by mundher** [comment]
I only tested my model on the NSFW dataset. The model trained using keras with theano backend

**Comment by KeyKy** [comment]
Do you train your model from scratch?

**Comment by mundher** [comment]
Yes, I trained from scratch. The theory behind this work is here https://arxiv.org/abs/1612.09506
