### ISSUE TITLE
where I can find the dataset

### ISSUE THREAD

**Issue by angelfish91** [mundher/NSFW#2]
It would best to public the dataset

**Comment by mundher** [comment]
Hi,
The dataset only available for research purpose. If you are an academic,
please sign the attached LA and send it from your academic email.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
