### ISSUE TITLE
data set production

### ISSUE THREAD

**Issue by yunhai0920** [mundher/NSFW#4]
hi,I am sorry to bother you, but i want to kown how do you make a data set? nsfw set maybe easy to classify,but the types of sfw images are too complex and huge, you can't include all the categories of sfw image.

**Comment by Quantumlyy** [comment]
Bump

**Comment by mundher** [comment]
Images have been randomly collected from online websites. Unfortunately, I don't have the number of images for each category. However, as I mentioned in the readme, if you are a researcher you are welcome to email me to get access to the dataset
