### ISSUE TITLE
NSFW Dataset

### ISSUE THREAD

**Issue by asrichardson821** [mundher/NSFW#5]
Hello Mundher,

I am interested in extending the research you have produced. I have your paper, Smart Content Recognition from Images Using a Mixture of Convolutional Neural Networks. Would you be able to direct me to how I can obtain the dataset?  I am a CS Ph.D. student (Computer Vision/AI specialized) and looking to narrow my dissertation to a related area of work.

Thanks,

Anthony

**Comment by mundher** [comment]
Thank you for your interest.
The dataset is available for research only. If you are a researcher, please
sign the attached License Agreement and send it back to me from your
ACADEMIC EMAIL.

**Comment by asrichardson821** [comment]
Thank you for your quick reply; can you please attach the agreement? It was not attached to your last post. I will complete and email from my academic email once I have received the file.

**Comment by mundher** [comment]
here it is the License Agreement 
https://drive.google.com/open?id=1MrzzFxQ9t56i9d3gMAI3SaHXfVd1UUDt
