### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by ericborn** [mundher/NSFW#6]
Hi Mundher,

Would it be possible to get access to the dataset you trained this model with? I'm working on a similar project and am having trouble finding a tagged nsfw dataset.

Thanks!

**Comment by mundher** [comment]
The dataset is available for research purposes. If you're an academic, please [fill out the form](https://drive.google.com/file/d/1M8QbER_88npl51aUXhSEfK11kf1kfziI/view?usp=drive_link) and send it from your academic email

**Comment by mundher** [comment]
The dataset is available for research purposes. If you're an academic, please [fill out the form](https://drive.google.com/file/d/1M8QbER_88npl51aUXhSEfK11kf1kfziI/view?usp=drive_link) and send it from your academic email
